package sdk

import (
	"context"
	"fmt"
	"time"
)

// CommandService handles dispatching commands to PBM agents.
// It performs pre-flight checks (lock validation) before sending.
//
// Most callers should prefer the higher-level methods on [BackupService] and
// [RestoreService] (Start, Delete, Cancel) which build the correct command
// internally. Use CommandService directly only when you need low-level control
// over command construction.
//
// Example — dispatch a backup command directly:
//
//	cmd := sdk.BackupCommand{
//	    Name: "2026-02-20T10:00:00Z",
//	    Type: sdk.BackupTypeLogical,
//	}
//	result, err := client.Commands.Send(ctx, cmd)
//	if err != nil {
//	    var concurrent *sdk.ConcurrentOperationError
//	    if errors.As(err, &concurrent) {
//	        fmt.Printf("blocked by %s (opid: %s)\n", concurrent.Type, concurrent.OPID)
//	    }
//	    return err
//	}
//	fmt.Printf("dispatched, opid: %s\n", result.OPID)
type CommandService interface {
	// Send dispatches a command to PBM agents and returns the result.
	// It calls [CommandService.CheckLock] internally before dispatching;
	// callers do not need to check for concurrent operations separately.
	//
	// Returns a [*ConcurrentOperationError] if a non-stale PBM operation is
	// already running.
	Send(ctx context.Context, cmd Command) (CommandResult, error)

	// CheckLock verifies no non-stale PBM operation is currently running.
	// Returns a [*ConcurrentOperationError] if one is, nil otherwise.
	//
	// A lock is considered stale when its heartbeat is older than PBM's
	// stale frame threshold relative to the cluster time.
	CheckLock(ctx context.Context) error
}

// Command is a sealed interface representing a PBM command.
// Only types defined in this package can implement it.
type Command interface {
	kind() string // unexported method prevents external implementations
}

// CommandResult is returned when a command is dispatched to PBM agents.
type CommandResult struct {
	// OPID is the operation ID (MongoDB ObjectID hex string) assigned to the
	// dispatched command. Use it with [BackupService.GetByOpID] to look up
	// the resulting backup metadata.
	OPID string
}

// StartBackupCommand is a sealed interface for backup initiation variants.
// Each variant represents a specific backup strategy with only the fields
// that are valid for that strategy. There are currently two implementations:
//   - [StartLogicalBackup] starts a logical (mongodump-based) backup.
//   - [StartIncrementalBackup] starts an incremental backup.
//
// Most callers should use [BackupService.Start], which auto-generates the
// backup name internally.
type StartBackupCommand interface {
	Command
	startBackupCommand() // seal to this package
}

// StartLogicalBackup requests a logical (mongodump-based) backup.
type StartLogicalBackup struct {
	// ConfigName selects the storage profile target. Zero value and
	// [MainConfig] both route to the main PBM storage configuration.
	ConfigName ConfigName

	// Compression overrides the server-configured compression algorithm.
	// Zero value uses the server default.
	Compression CompressionType

	// CompressionLevel overrides the server-configured compression level.
	// Valid values depend on the compression algorithm. Nil uses the server
	// default.
	CompressionLevel *int

	// Namespaces limits the backup to specific databases or collections
	// (e.g. ["mydb.mycol"]). Nil means a full backup of all namespaces.
	Namespaces []string

	name string // auto-generated by BackupService.Start; set before dispatch
}

func (c StartLogicalBackup) kind() string        { return fmt.Sprintf("%T", c) }
func (c StartLogicalBackup) startBackupCommand() {}

// StartIncrementalBackup requests an incremental backup. Incremental backups
// capture only the changes since the previous backup in the chain.
type StartIncrementalBackup struct {
	// ConfigName selects the storage profile target. Zero value and
	// [MainConfig] both route to the main PBM storage configuration.
	ConfigName ConfigName

	// Compression overrides the server-configured compression algorithm.
	// Zero value uses the server default.
	Compression CompressionType

	// CompressionLevel overrides the server-configured compression level.
	// Valid values depend on the compression algorithm. Nil uses the server
	// default.
	CompressionLevel *int

	// Base starts a new incremental backup chain when true. When false,
	// the backup extends the existing chain.
	Base bool

	name string // auto-generated by BackupService.Start; set before dispatch
}

func (c StartIncrementalBackup) kind() string        { return fmt.Sprintf("%T", c) }
func (c StartIncrementalBackup) startBackupCommand() {}

// StartRestoreCommand is a sealed interface for restore initiation variants.
// Each variant represents a specific restore strategy:
//   - [StartSnapshotRestore] restores from a backup snapshot as-is.
//   - [StartPITRRestore] restores to a specific point in time by replaying
//     oplog entries after restoring the base snapshot.
//
// Most callers should use [RestoreService.Start], which auto-generates the
// restore name internally.
type StartRestoreCommand interface {
	Command
	startRestoreCommand() // seal to this package
}

// StartSnapshotRestore requests a restore from a backup snapshot.
type StartSnapshotRestore struct {
	// BackupName is the source backup to restore from. Required.
	BackupName string

	// Namespaces limits the restore to specific databases or collections.
	// Nil means a full restore of all namespaces in the backup.
	Namespaces []string

	// NamespaceFrom is the source namespace for namespace remapping
	// (e.g. "sourceDB.sourceColl"). Must be set together with NamespaceTo.
	NamespaceFrom string

	// NamespaceTo is the target namespace for namespace remapping
	// (e.g. "targetDB.targetColl"). Must be set together with NamespaceFrom.
	NamespaceTo string

	// UsersAndRoles includes users and roles in the restore when true.
	UsersAndRoles bool

	// RSMap maps source replica set names to target replica set names
	// for cross-cluster restores (e.g. {"srcRS": "dstRS"}).
	RSMap map[string]string

	name string // auto-generated by RestoreService.Start; set before dispatch
}

func (c StartSnapshotRestore) kind() string         { return fmt.Sprintf("%T", c) }
func (c StartSnapshotRestore) startRestoreCommand() {}

// StartPITRRestore requests a point-in-time restore. The restore replays
// oplog entries from the base backup up to the specified target timestamp.
type StartPITRRestore struct {
	// BackupName is the source backup to restore from. Required.
	BackupName string

	// Target is the point-in-time to restore to. Must fall within a
	// continuous oplog timeline that starts from the named backup.
	Target Timestamp

	// Namespaces limits the restore to specific databases or collections.
	// Nil means a full restore of all namespaces in the backup.
	Namespaces []string

	// NamespaceFrom is the source namespace for namespace remapping.
	// Must be set together with NamespaceTo.
	NamespaceFrom string

	// NamespaceTo is the target namespace for namespace remapping.
	// Must be set together with NamespaceFrom.
	NamespaceTo string

	// UsersAndRoles includes users and roles in the restore when true.
	UsersAndRoles bool

	// RSMap maps source replica set names to target replica set names
	// for cross-cluster restores.
	RSMap map[string]string

	name string // auto-generated by RestoreService.Start; set before dispatch
}

func (c StartPITRRestore) kind() string         { return fmt.Sprintf("%T", c) }
func (c StartPITRRestore) startRestoreCommand() {}

// DeleteBackupCommand is a sealed interface for backup deletion variants.
// There are exactly two implementations:
//   - [DeleteBackupByName] deletes a single backup by name.
//   - [DeleteBackupsBefore] deletes all backups older than a timestamp,
//     optionally filtered by type and storage profile.
//
// Most callers should use [BackupService.Delete] instead of dispatching
// through [CommandService] directly.
type DeleteBackupCommand interface {
	Command
	deleteBackupCommand() // seal to this package
}

// DeleteBackupByName requests deletion of a single backup and its data
// from storage.
type DeleteBackupByName struct {
	// Name is the backup to delete (e.g. "2026-02-20T10:00:00Z").
	Name string
}

func (c DeleteBackupByName) kind() string         { return fmt.Sprintf("%T", c) }
func (c DeleteBackupByName) deleteBackupCommand() {}

// DeleteBackupsBefore requests deletion of all backups older than a
// timestamp. The deletion is processed asynchronously by PBM agents.
type DeleteBackupsBefore struct {
	// OlderThan is the cutoff time. All backups with a start time before
	// this value are candidates for deletion. Required — zero value is
	// rejected with an error.
	OlderThan time.Time

	// Type filters deletion to a specific backup type. Zero value means
	// all types.
	Type BackupType

	// ConfigName filters deletion to backups on a specific storage profile.
	// Zero value means all profiles.
	ConfigName ConfigName
}

func (c DeleteBackupsBefore) kind() string         { return fmt.Sprintf("%T", c) }
func (c DeleteBackupsBefore) deleteBackupCommand() {}

// DeletePITRCommand is a sealed interface for PITR oplog chunk deletion
// variants. There are exactly two implementations:
//   - [DeletePITRBefore] deletes all oplog chunks older than a timestamp.
//   - [DeletePITRAll] deletes all oplog chunks (equivalent to
//     DeletePITRBefore with OlderThan set to the current time).
//
// Most callers should use [PITRService.Delete] instead of dispatching
// through [CommandService] directly.
type DeletePITRCommand interface {
	Command
	deletePITRCommand() // seal to this package
}

// DeletePITRBefore requests deletion of all PITR oplog chunks older than
// a timestamp. The deletion is processed asynchronously by PBM agents.
type DeletePITRBefore struct {
	// OlderThan is the cutoff time. All oplog chunks ending before this
	// value are candidates for deletion. Required — zero value is rejected
	// with an error.
	OlderThan time.Time
}

func (c DeletePITRBefore) kind() string       { return fmt.Sprintf("%T", c) }
func (c DeletePITRBefore) deletePITRCommand() {}

// DeletePITRAll requests deletion of all PITR oplog chunks. This is
// equivalent to [DeletePITRBefore] with OlderThan set to the current time.
type DeletePITRAll struct{}

func (c DeletePITRAll) kind() string       { return fmt.Sprintf("%T", c) }
func (c DeletePITRAll) deletePITRCommand() {}

// ResyncCommand is a sealed interface for storage resynchronization variants.
// Resync commands instruct PBM agents to re-read backup metadata from storage.
// There are exactly three implementations:
//   - [ResyncMain] resyncs the main storage configuration.
//   - [ResyncProfile] resyncs a single named storage profile.
//   - [ResyncAllProfiles] resyncs all storage profiles.
//
// Most callers should use [ConfigService.Resync] instead of dispatching
// through [CommandService] directly.
type ResyncCommand interface {
	Command
	resyncCommand() // seal to this package
}

// ResyncMain requests a resynchronization of the main storage configuration.
// PBM agents re-read backup and restore metadata from the main storage.
type ResyncMain struct {
	// IncludeRestores includes physical restore metadata in the resync
	// when true. Only relevant for physical backup storage.
	IncludeRestores bool
}

func (c ResyncMain) kind() string   { return fmt.Sprintf("%T", c) }
func (c ResyncMain) resyncCommand() {}

// ResyncProfile requests a resynchronization of a single named storage profile.
// PBM agents re-read backup metadata from the specified profile's storage.
type ResyncProfile struct {
	// Name is the storage profile to resync. Required.
	Name string

	// Clear removes existing backup metadata for this profile before
	// resyncing when true. Use this when the storage contents have changed
	// externally and stale metadata needs to be purged.
	Clear bool
}

func (c ResyncProfile) kind() string   { return fmt.Sprintf("%T", c) }
func (c ResyncProfile) resyncCommand() {}

// ResyncAllProfiles requests a resynchronization of all storage profiles.
// PBM agents re-read backup metadata from every configured profile's storage.
type ResyncAllProfiles struct {
	// Clear removes existing backup metadata for all profiles before
	// resyncing when true.
	Clear bool
}

func (c ResyncAllProfiles) kind() string   { return fmt.Sprintf("%T", c) }
func (c ResyncAllProfiles) resyncCommand() {}

// AddProfileCommand requests creation or replacement of a named storage profile.
// The storage field is unexported and populated by [ConfigService] from parsed YAML;
// callers cannot construct this command directly — use ConfigService instead.
type AddProfileCommand struct {
	// Name is the profile name to create or replace.
	Name string

	storage any // holds parsed PBM config.StorageConf; set by ConfigService
}

func (c AddProfileCommand) kind() string { return fmt.Sprintf("%T", c) }

// RemoveProfileCommand requests deletion of a named storage profile.
type RemoveProfileCommand struct {
	// Name is the profile to remove.
	Name string
}

func (c RemoveProfileCommand) kind() string { return fmt.Sprintf("%T", c) }

// CancelBackupCommand requests cancellation of the currently running backup.
type CancelBackupCommand struct{}

func (c CancelBackupCommand) kind() string { return fmt.Sprintf("%T", c) }

// BackupResult is returned by [BackupService.Start].
type BackupResult struct {
	CommandResult

	// Name is the auto-generated backup name (RFC 3339 UTC timestamp).
	// Use it with [BackupService.Get] or [BackupService.Wait] to track progress.
	Name string
}

// RestoreResult is returned by [RestoreService.Start].
type RestoreResult struct {
	CommandResult

	// Name is the auto-generated restore name (RFC 3339 UTC timestamp).
	// Use it with [RestoreService.Get] or [RestoreService.Wait] to track progress.
	Name string
}
