package sdk

import (
	"fmt"
	"strings"
	"time"
)

// validator is implemented by all command types. Service impls call
// validateAndCheckLock, which invokes Validate before checking for
// concurrent PBM operations.
type validator interface {
	Validate() error
}

// CommandResult is returned when a command is dispatched to PBM agents.
type CommandResult struct {
	// OPID is the operation ID (MongoDB ObjectID hex string) assigned to the
	// dispatched command. Use it with [BackupService.GetByOpID] to look up
	// the resulting backup metadata.
	OPID string
}

// StartBackupCommand is a sealed interface for backup initiation variants.
// Each variant represents a specific backup strategy with only the fields
// that are valid for that strategy. There are currently three implementations:
//   - [StartLogicalBackup] starts a logical (mongodump-based) backup.
//   - [StartPhysicalBackup] starts a physical (WiredTiger file-level) backup.
//   - [StartIncrementalBackup] starts an incremental backup.
//
// Most callers should use [BackupService.Start], which auto-generates the
// backup name internally.
type StartBackupCommand interface {
	Validate() error
	startBackupCommand() // seal to this package
}

// StartLogicalBackup requests a logical (mongodump-based) backup.
type StartLogicalBackup struct {
	// ConfigName selects the storage profile target. Zero value and
	// [MainConfig] both route to the main PBM storage configuration.
	ConfigName ConfigName

	// Compression overrides the server-configured compression algorithm.
	// Zero value uses the server default.
	Compression CompressionType

	// CompressionLevel overrides the server-configured compression level.
	// Valid values depend on the compression algorithm. Nil uses the server
	// default.
	CompressionLevel *int

	// Namespaces limits the backup to specific databases or collections
	// (e.g. ["mydb.mycol"]). Nil means a full backup of all namespaces.
	Namespaces []string

	// UsersAndRoles includes authentication data (users and roles) in a
	// selective backup. Only valid when Namespaces is non-empty and all
	// entries are whole-database patterns (e.g. "db.*"), not specific
	// collections. Ignored for full backups.
	UsersAndRoles bool

	// NumParallelColls overrides the number of collections to dump in
	// parallel. Nil uses the server-configured default.
	NumParallelColls *int

	name string // auto-generated by BackupService.Start; set before dispatch
}

func (c StartLogicalBackup) startBackupCommand() {}

// Validate checks that UsersAndRoles is only set for selective backups
// with whole-database namespace patterns.
func (c StartLogicalBackup) Validate() error {
	return validateUsersAndRoles("start backup", c.UsersAndRoles, c.Namespaces)
}

// StartPhysicalBackup requests a physical (WiredTiger file-level) backup.
// Physical backups copy raw data files via PSMDB's $backupCursor and are
// typically faster than logical backups for large datasets. They require
// Percona Server for MongoDB — vanilla MongoDB does not support them.
//
// Physical backups do not support namespace filtering or parallel collection
// dumping — they always back up the entire cluster at the storage engine level.
type StartPhysicalBackup struct {
	// ConfigName selects the storage profile target. Zero value and
	// [MainConfig] both route to the main PBM storage configuration.
	ConfigName ConfigName

	// Compression overrides the server-configured compression algorithm.
	// Zero value uses the server default.
	Compression CompressionType

	// CompressionLevel overrides the server-configured compression level.
	// Valid values depend on the compression algorithm. Nil uses the server
	// default.
	CompressionLevel *int

	name string // auto-generated by BackupService.Start; set before dispatch
}

func (c StartPhysicalBackup) startBackupCommand() {}
func (c StartPhysicalBackup) Validate() error     { return nil }

// StartIncrementalBackup requests an incremental backup. Incremental backups
// capture only the changes since the previous backup in the chain.
type StartIncrementalBackup struct {
	// ConfigName selects the storage profile target. Zero value and
	// [MainConfig] both route to the main PBM storage configuration.
	ConfigName ConfigName

	// Compression overrides the server-configured compression algorithm.
	// Zero value uses the server default.
	Compression CompressionType

	// CompressionLevel overrides the server-configured compression level.
	// Valid values depend on the compression algorithm. Nil uses the server
	// default.
	CompressionLevel *int

	// Base starts a new incremental backup chain when true. When false,
	// the backup extends the existing chain.
	Base bool

	name string // auto-generated by BackupService.Start; set before dispatch
}

func (c StartIncrementalBackup) startBackupCommand() {}
func (c StartIncrementalBackup) Validate() error     { return nil }

// StartRestoreCommand is a sealed interface for restore initiation variants.
// Each variant represents a specific restore strategy:
//   - [StartSnapshotRestore] restores from a backup snapshot as-is.
//   - [StartPITRRestore] restores to a specific point in time by replaying
//     oplog entries after restoring the base snapshot.
//
// Most callers should use [RestoreService.Start], which auto-generates the
// restore name internally.
type StartRestoreCommand interface {
	Validate() error
	startRestoreCommand() // seal to this package
}

// StartSnapshotRestore requests a restore from a backup snapshot.
type StartSnapshotRestore struct {
	// BackupName is the source backup to restore from. Required.
	BackupName string

	// Namespaces limits the restore to specific databases or collections.
	// Nil means a full restore of all namespaces in the backup.
	Namespaces []string

	// NamespaceFrom is the source namespace for namespace remapping
	// (e.g. "sourceDB.sourceColl"). Must be set together with NamespaceTo.
	NamespaceFrom string

	// NamespaceTo is the target namespace for namespace remapping
	// (e.g. "targetDB.targetColl"). Must be set together with NamespaceFrom.
	NamespaceTo string

	// UsersAndRoles includes users and roles in the restore when true.
	UsersAndRoles bool

	// RSMap maps source replica set names to target replica set names
	// for cross-cluster restores (e.g. {"srcRS": "dstRS"}).
	RSMap map[string]string

	// NumParallelColls overrides the number of collections to restore in
	// parallel. Nil uses the server-configured default.
	NumParallelColls *int

	// NumInsertionWorkers overrides the number of insertion workers per
	// collection. Nil uses the server-configured default.
	NumInsertionWorkers *int

	// AllowPartlyDone allows restoring from a backup that completed only
	// partially (some replica sets succeeded). Nil uses the server default.
	AllowPartlyDone *bool

	// Fallback enables fallback mode for restore operations. Nil uses the
	// server-configured default.
	Fallback *bool

	name string // auto-generated by RestoreService.Start; set before dispatch
}

func (c StartSnapshotRestore) startRestoreCommand() {}

// Validate checks that BackupName is set, namespace remapping fields
// are paired, and UsersAndRoles constraints are met.
func (c StartSnapshotRestore) Validate() error {
	if c.BackupName == "" {
		return fmt.Errorf("start restore: backup name is required")
	}
	if err := validateNamespaceRemap("start restore", c.NamespaceFrom, c.NamespaceTo); err != nil {
		return err
	}
	return validateUsersAndRoles("start restore", c.UsersAndRoles, c.Namespaces)
}

// StartPITRRestore requests a point-in-time restore. The restore replays
// oplog entries from the base backup up to the specified target timestamp.
type StartPITRRestore struct {
	// BackupName is the source backup to restore from. Required.
	BackupName string

	// Target is the point-in-time to restore to. Must fall within a
	// continuous oplog timeline that starts from the named backup.
	Target Timestamp

	// Namespaces limits the restore to specific databases or collections.
	// Nil means a full restore of all namespaces in the backup.
	Namespaces []string

	// NamespaceFrom is the source namespace for namespace remapping.
	// Must be set together with NamespaceTo.
	NamespaceFrom string

	// NamespaceTo is the target namespace for namespace remapping.
	// Must be set together with NamespaceFrom.
	NamespaceTo string

	// UsersAndRoles includes users and roles in the restore when true.
	UsersAndRoles bool

	// RSMap maps source replica set names to target replica set names
	// for cross-cluster restores.
	RSMap map[string]string

	// NumParallelColls overrides the number of collections to restore in
	// parallel. Nil uses the server-configured default.
	NumParallelColls *int

	// NumInsertionWorkers overrides the number of insertion workers per
	// collection. Nil uses the server-configured default.
	NumInsertionWorkers *int

	// AllowPartlyDone allows restoring from a backup that completed only
	// partially (some replica sets succeeded). Nil uses the server default.
	AllowPartlyDone *bool

	// Fallback enables fallback mode for restore operations. Nil uses the
	// server-configured default.
	Fallback *bool

	name string // auto-generated by RestoreService.Start; set before dispatch
}

func (c StartPITRRestore) startRestoreCommand() {}

// Validate checks that BackupName and Target are set, namespace remapping
// fields are paired, and UsersAndRoles constraints are met.
func (c StartPITRRestore) Validate() error {
	if c.BackupName == "" {
		return fmt.Errorf("start pitr restore: backup name is required")
	}
	if c.Target.IsZero() {
		return fmt.Errorf("start pitr restore: target timestamp is required")
	}
	if err := validateNamespaceRemap("start pitr restore", c.NamespaceFrom, c.NamespaceTo); err != nil {
		return err
	}
	return validateUsersAndRoles("start pitr restore", c.UsersAndRoles, c.Namespaces)
}

// DeleteBackupCommand is a sealed interface for backup deletion variants.
// There are exactly two implementations:
//   - [DeleteBackupByName] deletes a single backup by name.
//   - [DeleteBackupsBefore] deletes all backups older than a timestamp,
//     optionally filtered by type and storage profile.
type DeleteBackupCommand interface {
	Validate() error
	deleteBackupCommand() // seal to this package
}

// DeleteBackupByName requests deletion of a single backup and its data
// from storage.
type DeleteBackupByName struct {
	// Name is the backup to delete (e.g. "2026-02-20T10:00:00Z").
	Name string
}

func (c DeleteBackupByName) deleteBackupCommand() {}

func (c DeleteBackupByName) Validate() error {
	if c.Name == "" {
		return fmt.Errorf("delete backup: name is required")
	}
	return nil
}

// DeleteBackupsBefore requests deletion of all backups older than a
// timestamp. The deletion is processed asynchronously by PBM agents.
type DeleteBackupsBefore struct {
	// OlderThan is the cutoff time. All backups with a start time before
	// this value are candidates for deletion. Required — zero value is
	// rejected with an error.
	OlderThan time.Time

	// Type filters deletion to a specific backup type. Zero value means
	// all types.
	Type BackupType

	// ConfigName filters deletion to backups on a specific storage profile.
	// Zero value means all profiles.
	ConfigName ConfigName
}

func (c DeleteBackupsBefore) deleteBackupCommand() {}

func (c DeleteBackupsBefore) Validate() error {
	if c.OlderThan.IsZero() {
		return fmt.Errorf("delete backups: older-than time must be set")
	}
	if c.OlderThan.After(time.Now().UTC()) {
		return fmt.Errorf("delete backups: older-than time %s is in the future",
			c.OlderThan.Format(time.RFC3339))
	}
	return nil
}

// DeletePITRCommand is a sealed interface for PITR oplog chunk deletion
// variants. There are exactly two implementations:
//   - [DeletePITRBefore] deletes all oplog chunks older than a timestamp.
//   - [DeletePITRAll] deletes all oplog chunks (equivalent to
//     DeletePITRBefore with OlderThan set to the current time).
type DeletePITRCommand interface {
	Validate() error
	deletePITRCommand() // seal to this package
}

// DeletePITRBefore requests deletion of all PITR oplog chunks older than
// a timestamp. The deletion is processed asynchronously by PBM agents.
type DeletePITRBefore struct {
	// OlderThan is the cutoff time. All oplog chunks ending before this
	// value are candidates for deletion. Required — zero value is rejected
	// with an error.
	OlderThan time.Time
}

func (c DeletePITRBefore) deletePITRCommand() {}

func (c DeletePITRBefore) Validate() error {
	if c.OlderThan.IsZero() {
		return fmt.Errorf("delete PITR chunks: older-than time must be set")
	}
	if c.OlderThan.After(time.Now().UTC()) {
		return fmt.Errorf("delete PITR chunks: older-than time %s is in the future",
			c.OlderThan.Format(time.RFC3339))
	}
	return nil
}

// DeletePITRAll requests deletion of all PITR oplog chunks. This is
// equivalent to [DeletePITRBefore] with OlderThan set to the current time.
type DeletePITRAll struct{}

func (c DeletePITRAll) deletePITRCommand() {}
func (c DeletePITRAll) Validate() error    { return nil }

// ResyncCommand is a sealed interface for storage resynchronization variants.
// Resync commands instruct PBM agents to re-read backup metadata from storage.
// There are exactly three implementations:
//   - [ResyncMain] resyncs the main storage configuration.
//   - [ResyncProfile] resyncs a single named storage profile.
//   - [ResyncAllProfiles] resyncs all storage profiles.
type ResyncCommand interface {
	Validate() error
	resyncCommand() // seal to this package
}

// ResyncMain requests a resynchronization of the main storage configuration.
// PBM agents re-read backup and restore metadata from the main storage.
type ResyncMain struct {
	// IncludeRestores includes physical restore metadata in the resync
	// when true. Only relevant for physical backup storage.
	IncludeRestores bool
}

func (c ResyncMain) resyncCommand()  {}
func (c ResyncMain) Validate() error { return nil }

// ResyncProfile requests a resynchronization of a single named storage profile.
// PBM agents re-read backup metadata from the specified profile's storage.
type ResyncProfile struct {
	// Name is the storage profile to resync. Required.
	Name string

	// Clear removes existing backup metadata for this profile before
	// resyncing when true. Use this when the storage contents have changed
	// externally and stale metadata needs to be purged.
	Clear bool
}

func (c ResyncProfile) resyncCommand() {}

func (c ResyncProfile) Validate() error {
	if c.Name == "" {
		return fmt.Errorf("resync profile: name is required")
	}
	return nil
}

// ResyncAllProfiles requests a resynchronization of all storage profiles.
// PBM agents re-read backup metadata from every configured profile's storage.
type ResyncAllProfiles struct {
	// Clear removes existing backup metadata for all profiles before
	// resyncing when true.
	Clear bool
}

func (c ResyncAllProfiles) resyncCommand()  {}
func (c ResyncAllProfiles) Validate() error { return nil }

// AddProfileCommand requests creation or replacement of a named storage profile.
// The storage field is unexported and populated by [ConfigService] from parsed YAML;
// callers cannot construct this command directly — use ConfigService instead.
type AddProfileCommand struct {
	// Name is the profile name to create or replace.
	Name string

	storage any // holds parsed PBM config.StorageConf; set by ConfigService
}

func (c AddProfileCommand) Validate() error { return nil }

// RemoveProfileCommand requests deletion of a named storage profile.
type RemoveProfileCommand struct {
	// Name is the profile to remove.
	Name string
}

func (c RemoveProfileCommand) Validate() error {
	if c.Name == "" {
		return fmt.Errorf("remove profile: name is required")
	}
	return nil
}

// CancelBackupCommand requests cancellation of the currently running backup.
type CancelBackupCommand struct{}

func (c CancelBackupCommand) Validate() error { return nil }

// BackupResult is returned by [BackupService.Start].
type BackupResult struct {
	CommandResult

	// Name is the auto-generated backup name (RFC 3339 UTC timestamp).
	// Use it with [BackupService.Get] or [BackupService.Wait] to track progress.
	Name string
}

// RestoreResult is returned by [RestoreService.Start].
type RestoreResult struct {
	CommandResult

	// Name is the auto-generated restore name (RFC 3339 UTC timestamp).
	// Use it with [RestoreService.Get] or [RestoreService.Wait] to track progress.
	Name string
}

// validateUsersAndRoles checks that UsersAndRoles is only set when
// namespaces are non-empty and all entries are whole-database patterns
// (ending with ".*"). This mirrors PBM's ValidateUsersAndRolesOpt.
func validateUsersAndRoles(op string, usersAndRoles bool, namespaces []string) error {
	if !usersAndRoles {
		return nil
	}
	if len(namespaces) == 0 {
		return fmt.Errorf("%s: users-and-roles is only valid for selective operations (namespaces must be set)", op)
	}
	for _, ns := range namespaces {
		if !strings.HasSuffix(ns, ".*") {
			return fmt.Errorf("%s: users-and-roles requires whole-database namespace patterns (\"db.*\"), got %q", op, ns)
		}
	}
	return nil
}

// validateNamespaceRemap checks that NamespaceFrom and NamespaceTo are
// either both set or both empty.
func validateNamespaceRemap(op, from, to string) error {
	if (from != "") != (to != "") {
		return fmt.Errorf("%s: namespace-from and namespace-to must be set together", op)
	}
	return nil
}
